---
- name: Set password policy
  hosts: all
  gather_facts: true
  become: true
  
  tasks:
    - name: Disable username in password and enforce it for root
      pamd:
        name: system-auth
        type: password
        control: requisite
        module_path: pam_pwquality.so
        module_arguments: 'try_first_pass 
          local_users_only
          retry=3 
          gecoscheck=1
          authtok_type= enforce_for_root'
        state: updated
