---
- name: TCP wrappers
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Configure /etc/hosts.allow
      blockinfile:
        path: /etc/hosts.allow
        block: |
          sshd: 178.94.125.98, LOCAL

    - name: Configure /etc/hosts.deny
      blockinfile:
        path: /etc/hosts.deny
        block: |
          sshd: ALL
          ALL : ALL

